### ISSUE TITLE
Support special keys in `/usr/include/X11/XF86keysym.h`

### ISSUE THREAD

**Issue by spikespaz** [d86leader/wzmach#6]
For raising and lowering volume, internal display brightness, etc. it would be nice to have support for keys such as:

```c
/* Backlight controls. */
#define XF86XK_MonBrightnessUp    0x1008FF02  /* Monitor/panel brightness */
#define XF86XK_MonBrightnessDown  0x1008FF03  /* Monitor/panel brightness */
...
/*
 * Keys found on some "Internet" keyboards.
 */
...
#define XF86XK_AudioLowerVolume	0x1008FF11   /* Volume control down        */
#define XF86XK_AudioMute	0x1008FF12   /* Mute sound from the system */
#define XF86XK_AudioRaiseVolume	0x1008FF13   /* Volume control up          */
#define XF86XK_AudioPlay	0x1008FF14   /* Start playing of audio >   */
#define XF86XK_AudioStop	0x1008FF15   /* Stop playing audio         */
#define XF86XK_AudioPrev	0x1008FF16   /* Previous track             */
#define XF86XK_AudioNext	0x1008FF17   /* Next track                 */
#define XF86XK_HomePage		0x1008FF18   /* Display user's home page   */
#define XF86XK_Mail		0x1008FF19   /* Invoke user's mail program */
#define XF86XK_Start		0x1008FF1A   /* Start application          */
#define XF86XK_Search		0x1008FF1B   /* Search                     */
#define XF86XK_AudioRecord	0x1008FF1C   /* Record audio application   */
```

These can be found in `/usr/include/X11/XF86keysym.h`, and regular keys found in `/usr/include/X11/keysymdef.h`.

I can see that currently the acceptable keys are defined by [`uinput::event::keyboard::Key`](https://docs.rs/uinput/latest/uinput/event/keyboard/enum.Key.html), I haven't searched through that crate very much, but I also see [`uinput::event::keyboard::key::Misc`](https://docs.rs/uinput/latest/uinput/event/keyboard/enum.Misc.html) which should do what I want.

**Comment by spikespaz** [comment]
Possibly use the enum [`uinput::event::keyboard::Keyboard`](https://docs.rs/uinput/latest/uinput/event/keyboard/enum.Keyboard.html) instead of `Key`.

https://github.com/d86leader/wzmach/blob/master/src/action/uinput_action.rs#L4-L8

**Comment by d86leader** [comment]
Oh, so that's where all the keys were. Yeah, should do that
